const rest = require('../../utils/rest.js');
const check = require('starkcore').check;
const Resource = require('../../utils/resource.js').Resource
const {parseObjects} = require('../../utils/parse.js');
const {PixKeyHolmes} = require('../pixKeyHolmes.js');
const pixKeyHolmesResource = require('../pixKeyHolmes.js').resource;


class Log extends Resource {
    /**
     *
     * PixKeyHolmes Log object
     *
     * @description Every time a PixKeyHolmes entity is modified, a corresponding PixKeyHolmes Log
     * is generated for the entity. This log is never generated by the
     * user.
     *
     * Attributes:
     * @param id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * @param holmes [PixKeyHolmes]: PixKeyHolmes entity to which the log refers to.
     * @param type [string]: type of the PixKeyHolmes event which triggered the log creation. ex: 'solving', 'solved'
     * @param errors [list of strings]: list of errors linked to this PixKeyHolmes event
     * @param created [string]: creation datetime for the log. ex: '2020-03-10 10:30:00.000'
     *
     */
    constructor({
                    id = null, holmes = null, type = null, errors = null, created = null
                }) {
        super(id);

        this.holmes = holmes === null ? null : parseObjects([holmes], pixKeyHolmesResource, PixKeyHolmes)[0];
        this.type = type;
        this.errors = errors;
        this.created = check.datetime(created);
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'PixKeyHolmesLog'};


exports.get = async function (id, { user } = {}) {
    /**
     *
     * Retrieve a specific PixKeyHolmes Log
     *
     * @description Receive a single PixKeyHolmes Log object previously created by the Stark Infra API by passing its id
     *
     * Parameters (required):
     * @param id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * @param user [Organization/Project object]: Organization or Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns PixKeyHolmes Log object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({ ids, limit, after, before, types, holmesIds, user } = {}) {
    /**
     *
     * Retrieve PixKeyHolmes Logs
     *
     * @description Receive a generator of PixKeyHolmes Log objects previously created in the Stark Infra API
     *
     * Parameters (optional):
     * @param ids [list of strings, default null]: Log ids to filter PixKeyHolmes Logs. ex: ['5656565656565656']
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null]: date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null]: date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ['solving', 'solved']
     * @param holmesIds [list of strings, default null]: list of PixKeyHolmes ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns generator of PixKeyHolmes Log objects with updated attributes
     *
     */
    let query = {
        ids: ids,
        limit: limit,
        after: after,
        before: before,
        types: types,
        holmesIds: holmesIds,
    };
    return rest.getList(resource, query, user);
};

exports.page = async function ({ cursor, ids, limit, after, before, types, holmesIds, user } = {}) {
    /**
     *
     * Retrieve paged PixKeyHolmes Logs
     *
     * @description Receive a list of up to 100 PixKeyHolmes Log objects previously created in the Stark Infra API and the cursor to the next page.
     * Use this function instead of query if you want to manually page your requests.
     *
     * Parameters (optional):
     * @param cursor [string, default null]: cursor returned on the previous page function call
     * @param ids [list of strings, default null]: Log ids to filter PixKeyHolmes Logs. ex: ['5656565656565656']
     * @param limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 35
     * @param after [string, default null]: date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null]: date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ['solving', 'solved']
     * @param holmesIds [list of strings, default null]: list of PixKeyHolmes ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Organization or Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns list of PixKeyHolmes Log objects with updated attributes and cursor to retrieve the next page of PixKeyHolmes Log objects
     *
     */
    let query = {
        cursor: cursor,
        ids: ids,
        limit: limit,
        after: after,
        before: before,
        types: types,
        holmesIds: holmesIds,
    };
    return rest.getPage(resource, query, user);
};
