const rest = require('../../utils/rest.js');
const check = require('../../utils/check.js');
const Resource = require('../../utils/resource.js').Resource


class Log extends Resource {
    /**
     *
     * IssuingInvoice Log object
     *
     * @description Every time an IssuingInvoice entity is modified, a corresponding IssuingInvoice Log
     * is generated for the entity. This log is never generated by the
     * user.
     *
     * Attributes:
     * @param id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * @param created [string]: creation datetime for the log. ex: '2020-03-10 10:30:00.000'
     * @param type [string]: type of the IssuingInvoice event which triggered the log creation. ex: 'processing' or 'success'
     * @param request [IssuingInvoice]: IssuingInvoice entity to which the log refers to.
     *
     */
    constructor({ id, created, type, invoice }) {
        super(id);
        this.created = check.datetime(created);
        this.type = type;
        this.invoice = invoice;
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'IssuingInvoiceLog'};


exports.get = async function (id, { user } = {}) {
    /**
     *
     * Retrieve a specific IssuingInvoice Log
     *
     * @description Receive a single IssuingInvoice Log object previously created by the Stark Infra API by passing its id
     *
     * Parameters (required):
     * @param id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * @param user [Organization/Project object]: Organization or Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns IssuingInvoice Log object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};


exports.query = async function ({ ids, types, after, before, limit, user } = {}) {
    /**
     *
     * Retrieve IssuingInvoice Logs
     *
     * @description Receive a generator of IssuingInvoice Log objects previously created in the Stark Infra API
     *
     * Parameters (optional):
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ["created", "paid"]
     * @param ids [list of strings, default null]: list of IssuingInvoice ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns list of IssuingInvoice Log objects with updated attributes
     *
     */
    let query = {
        ids: ids,
        types: types,
        after: after,
        before: before,
        limit: limit,
    };
    return rest.getList(resource, query, user);
};

exports.page = async function ({ cursor, ids, types, after, before, limit, user } = {}) {
    /**
     *
     * Retrieve paged IssuingInvoice Logs
     *
     * @description Receive a list of up to 100 IssuingInvoice.Log objects previously created in the Stark Infra API and the cursor to the next page.
     * Use this function instead of query if you want to manually page your requests.
     *
     * Parameters (optional):
     * @param cursor [string, default null]: cursor returned on the previous page function call
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ["created", "paid"]
     * @param ids [list of strings, default null]: list of IssuingInvoice ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns list of IssuingInvoice Log objects with updated attributes and cursor to retrieve the next page of IssuingInvoice objects
     *
     */
    let query = {
        cursor: cursor,
        ids: ids,
        types: types,
        after: after,
        before: before,
        limit: limit,
    };
    return rest.getPage(resource, query, user);
};
