const rest = require('../../utils/rest.js');
const check = require('core-node').check;
const Resource = require('../../utils/resource.js').Resource


class Log extends Resource {
    /**
     *
     * IndividualDocument Log object
     *
     * @description Every time an IndividualDocument entity is modified, a corresponding IndividualDocument Log
     * is generated for the entity. This log is never generated by the
     * user.
     *
     * Attributes:
     * @param id [string]: unique id returned when the log is created. ex: '5656565656565656'
     * @param document [IndividualDocument]: IndividualDocument entity to which the log refers to.
     * @param errors [list of strings]: list of errors linked to this IndividualDocument event
     * @param type [string]: type of the IndividualDocument event which triggered the log creation. ex: "created", "canceled", "processing", "failed", "success"
     * @param created [string]: creation datetime for the log. ex: '2020-03-10 10:30:00.000'
     *
     */
    constructor({ 
                    id = null, document = null, errors = null, type = null, created = null
                }) {
        super(id);
        this.document = document;
        this.errors = errors;
        this.type = type;
        this.created = check.datetime(created);
    }
}

exports.Log = Log;
let resource = {'class': exports.Log, 'name': 'IndividualDocumentLog'};


exports.get = async function (id, { user } = {}) {
    /**
     *
     * Retrieve a specific IndividualDocument Log
     *
     * @description Receive a single IndividualDocument Log object previously created by the Stark Infra API by passing its id
     *
     * Parameters (required):
     * @param id [string]: object unique id. ex: '5656565656565656'
     *
     * Parameters (optional):
     * @param user [Organization/Project object]: Organization or Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns IndividualDocument Log object with updated attributes
     *
     */
    return rest.getId(resource, id, user);
};

exports.query = async function ({ limit, after, before, types, documentIds, user } = {}) {
    /**
     *
     * Retrieve IndividualDocument Logs
     *
     * @description Receive a generator of IndividualDocument Log objects previously created in the Stark Infra API
     *
     * Parameters (optional):
     * @param limit [integer, default null]: maximum number of objects to be retrieved. Unlimited if null. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ["created", "canceled", "processing", "failed", "success"]
     * @param documentIds [list of strings, default []]: list of IndividualDocument ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns list of IndividualDocument Log objects with updated attributes
     *
     */
    let query = {
        limit: limit,
        after: after,
        before: before,
        types: types,
        documentIds: documentIds,
    };
    return rest.getList(resource, query, user);
};

exports.page = async function ({ cursor, ids, limit, after, before, types, documentIds, user } = {}) {
    /**
     *
     * Retrieve paged IndividualDocument Logs
     *
     * @description Receive a list of up to 100 IndividualDocument.Log objects previously created in the Stark Infra API and the cursor to the next page.
     * Use this function instead of query if you want to manually page your documents.
     *
     * Parameters (optional):
     * @param cursor [string, default null]: cursor returned on the previous page function call
     * @param limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 35
     * @param after [string, default null] date filter for objects created only after specified date. ex: '2020-03-10'
     * @param before [string, default null] date filter for objects created only before specified date. ex: '2020-03-10'
     * @param types [list of strings, default null]: filter retrieved objects by types. ex: ["created", "canceled", "processing", "failed", "success"]
     * @param documentIds [list of strings, default []]: list of IndividualDocument ids to filter retrieved objects. ex: ['5656565656565656', '4545454545454545']
     * @param user [Organization/Project object, default null]: Project object. Not necessary if starkinfra.user was set before function call
     *
     * Return:
     * @returns list of IndividualDocument Log objects with updated attributes and cursor to retrieve the next page of IndividualDocument Log objects
     *
     */
    let query = {
        cursor: cursor,
        ids: ids,
        limit: limit,
        after: after,
        before: before,
        types: types,
        documentIds: documentIds,
    };
    return rest.getPage(resource, query, user);
};
